application: stochssapp
version: 1
runtime: python27
api_version: 1
threadsafe: no

handlers:
- url: /static/ico/favicon.ico
  static_files: static/ico/favicon.ico
  upload: static/ico/favicon.ico
- url: /static/css
  static_dir: static/css
- url: /static/img
  static_dir: static/img
- url: /static/js
  static_dir: static/js


- url: /.*
  script: stochssapp.app
  login: required
  auth_fail_action: redirect

libraries:
- name: jinja2
  version: latest
- name: lxml
  version: latest
